#include <chicken3421/chicken3421.hpp>

#include <glm/glm.hpp>
#include <glm/ext.hpp>

#include <ass3/loader.hpp>

namespace loader {

	std::vector<std::string> worldNames = {
		"Basic Super Flat World",
		"Wooly World",
		"Iron World",
		"Classic Sky Block",
		"Parkour Course",
		"Parkour Course 2: Marccoin in the Tower"
	};

	void printOutPresets() {
		std::cout << "Presets:\n";
		int counter = 0;
		for (auto name : worldNames) {
			std::cout << counter << " -> " << name.c_str() << "\n";
			counter++; 
		}
		return;
	}

	void loadWorld(std::vector<scene::miniBlockData> *list, int worldType) {
		std::cout << "\n";
		try {
			std::cout << worldNames.at(worldType) << " selected.\n";
		} catch (std::out_of_range) {
			std::cout << worldNames.at(0) << " selected.\n";
		}
		
		std::vector<glm::vec2> listOfPositions;
		switch (worldType) {
			case 1:
				list->emplace_back(scene::miniBlockData("gray", glm::vec3(0,0,0), false, true));
				list->emplace_back(scene::miniBlockData("white", glm::vec3(0,1,0), false, true));
				break;
			case 2:
				list->emplace_back(scene::miniBlockData("raw_iron", glm::vec3(0,0,0), false, true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(0,1,0), false, true));
				break;
			case 3:
				list->emplace_back(scene::miniBlockData("barrel", glm::vec3(0,3,0), true));
				// Generating land
				listOfPositions = {
					{-1, 0},
					{ 0, 0},
					{ 1, 0},
					{-1, 1},
					{ 0, 1},
					{ 1, 1},
					{-1, 2},
					{ 0, 2},
					{ 1, 2},
					{-1, 3},
					{ 0, 3},
					{ 1, 3},
					{-1, 4},
					{ 0, 4},
					{ 1, 4},
					{-1, 5},
					{ 0, 5},
					{ 1, 5},
					{ 1, 5},
					{ 2, 3},
					{ 2, 4},
					{ 2, 5},
					{ 3, 3},
					{ 3, 4},
					{ 3, 5},
					{ 4, 3},
					{ 4, 4},
					{ 4, 5},
				};
				for (auto i : listOfPositions) {
					list->emplace_back(scene::miniBlockData("dirt", glm::vec3(i.x,0,i.y), true));
					list->emplace_back(scene::miniBlockData("dirt", glm::vec3(i.x,1,i.y), true));
					if (i.x == 4 && i.y == 5) {
						list->emplace_back(scene::miniBlockData("dirt", glm::vec3(i.x,2,i.y), true));

						// Creating the tree
						list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(i.x,3,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(i.x,4,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(i.x,5,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(i.x,6,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(i.x,7,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(i.x,8,i.y), true));
						// Creating the leaves
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,9,i.y), true)); // +
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,9,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,9,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,9,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,9,i.y + 1), true));

						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,8,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,8,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,8,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,8,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,8,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,8,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,8,i.y + 1), true));

						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,7,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,7,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,7,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,7,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,7,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,7,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,7,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,7,i.y - 1), true));

						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,7,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,7,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,7,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,7,i.y + 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,7,i.y + 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,7,i.y + 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,7,i.y + 2), true));
						//
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,7,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,7,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,7,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,7,i.y - 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,7,i.y - 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,7,i.y - 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,7,i.y - 2), true));

						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,6,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,6,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,6,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,6,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,6,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,6,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,6,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,6,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,6,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,6,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,6,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 2,6,i.y + 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,6,i.y + 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,6,i.y + 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,6,i.y + 2), true));
						//
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,6,i.y), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,6,i.y + 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,6,i.y - 1), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 2,6,i.y - 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x - 1,6,i.y - 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x,6,i.y - 2), true));
						list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(i.x + 1,6,i.y - 2), true));
					} else {
						list->emplace_back(scene::miniBlockData("grass_block", glm::vec3(i.x,2,i.y), true));
					}
				}
				break;
			case 4:
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-13, 11, -7), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-13, 12, -6), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-13, 12, -5), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-13, 12, 0), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-13, 15, -5), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-12, 0, 10), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-12, 0, 11), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-12, 3, 10), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-11, 0, 10), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-11, 0, 11), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-11, 0, 12), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-11, 3, 11), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-10, 0, 11), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-10, 0, 12), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-10, 0, 13), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-10, 3, 12), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-9, 0, 12), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-9, 0, 13), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-9, 0, 14), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-9, 3, 13), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-9, 9, -7), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-9, 10, -6), true));
				list->emplace_back(scene::miniBlockData("copper_block", glm::vec3(-8, 0, 13), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-8, 0, 14), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-8, 3, 14), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-8, 7, -7), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-8, 8, -6), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-7, 5, -7), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-7, 6, -6), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-6, 3, -7), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-6, 4, -6), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(-3, 0, 19), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(-2, 3, -7), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(0, 0, 19), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 1), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 2), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 4), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 5), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(0, 3, 0), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(0, 3, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(1, 2, 0), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(1, 2, 1), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(1, 2, 2), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(1, 2, 3), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(1, 2, 4), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(1, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(1, 2, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(2, 0, -14), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(2, 1, -13), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(2, 2, -7), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(2, 2, 0), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(2, 2, 1), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(2, 2, 2), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(2, 2, 3), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(2, 2, 4), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(2, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(2, 2, 6), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(3, 0, 21), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(3, 2, -12), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(3, 2, 0), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(3, 2, 1), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(3, 2, 2), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(3, 2, 3), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(3, 2, 4), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(3, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(3, 2, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(4, 2, 0), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(4, 2, 1), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(4, 2, 2), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(4, 2, 3), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(4, 2, 4), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(4, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(4, 2, 6), true));
				list->emplace_back(scene::miniBlockData("yellow", glm::vec3(4, 3, 8), true));
				list->emplace_back(scene::miniBlockData("yellow", glm::vec3(4, 3, 10), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(4, 6, 8), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(5, 2, 0), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(5, 2, 1), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(5, 2, 2), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(5, 2, 3), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(5, 2, 4), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(5, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(5, 2, 6), true));
				list->emplace_back(scene::miniBlockData("yellow", glm::vec3(5, 2, 12), true));
				list->emplace_back(scene::miniBlockData("sea_lantern", glm::vec3(5, 4, -7), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(6, 0, 20), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(6, 0, 21), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(6, 0, 22), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 1), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 2), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 4), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 5), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(6, 3, 0), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(6, 3, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(7, 0, -14), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(7, 0, 20), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(7, 0, 21), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(7, 0, 22), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(7, 1, 19), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 1, 21), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(7, 1, 23), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 2, 21), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(7, 3, -15), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(7, 3, -14), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(7, 3, -13), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 3, 21), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 4, 21), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 5, 21), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 6, 21), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 7, 21), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(7, 8, 21), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 0, -14), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(8, 0, 20), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(8, 0, 21), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(8, 0, 22), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 3, -15), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 3, -14), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 3, -13), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 3, -9), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 3, -8), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 3, -7), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 6, -9), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 6, -8), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(8, 6, -7), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(9, 0, -14), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(9, 1, 21), true));
				list->emplace_back(scene::miniBlockData("yellow", glm::vec3(9, 2, 12), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(9, 3, -15), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(9, 3, -14), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(9, 3, -13), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(10, 0, -14), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 2, 14), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 8, -6), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 8, -5), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 8, -4), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 8, -3), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 9, -6), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 9, -5), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 9, -4), true));
				list->emplace_back(scene::miniBlockData("glass", glm::vec3(14, 9, -3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(15, 0, -14), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 3, 10), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 4, 7), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 5, 4), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 7, -6), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 7, -5), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 7, -4), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(15, 7, -3), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(17, 6, 1), true));
				break;
			case 5:
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 1, -3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 2, -1), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-11, 2, 15), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-11, 2, 21), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(-11, 2, 24), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 3, 1), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 4, 3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 5, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 6, 7), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 7, 9), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 7, 10), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 7, 11), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 9, 7), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-11, 10, 9), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-7, 2, 24), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-6, 1, -3), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-5, 1, -3), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-5, 2, 24), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-4, 1, -3), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(-4, 2, 24), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(-3, 1, -3), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(-3, 2, 24), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(-2, 1, -3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 1), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 2), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 4), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(0, 2, 5), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(0, 3, 0), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(0, 3, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(1, 0, -3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(1, 2, 0), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(1, 2, 1), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(1, 2, 2), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(1, 2, 3), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(1, 2, 4), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(1, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(1, 2, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(2, 2, 0), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(2, 2, 1), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(2, 2, 2), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(2, 2, 3), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(2, 2, 4), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(2, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(2, 2, 6), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(3, 0, 24), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(3, 2, -3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(3, 2, 0), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(3, 2, 1), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(3, 2, 2), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(3, 2, 3), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(3, 2, 4), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(3, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(3, 2, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(4, 2, 0), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(4, 2, 1), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(4, 2, 2), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(4, 2, 3), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(4, 2, 4), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(4, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(4, 2, 6), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(5, 2, 0), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(5, 2, 1), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(5, 2, 2), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(5, 2, 3), true));
				list->emplace_back(scene::miniBlockData("obsidian", glm::vec3(5, 2, 4), true));
				list->emplace_back(scene::miniBlockData("iron_block", glm::vec3(5, 2, 5), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(5, 2, 6), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(6, 1, 24), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 1), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 2), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 3), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 4), true));
				list->emplace_back(scene::miniBlockData("red", glm::vec3(6, 2, 5), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(6, 3, 0), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(6, 3, 6), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(7, 12, -13), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(7, 12, -12), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(7, 13, -13), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(8, 11, -13), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(8, 12, -13), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(8, 12, -12), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(8, 13, -13), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(9, 2, 24), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(9, 5, 22), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(9, 6, 24), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(9, 9, 22), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(9, 10, 24), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(9, 11, -13), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(9, 12, -14), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(9, 12, -13), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(9, 13, 22), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(10, 13, -13), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 3, 24), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 4, 22), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 7, 24), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 8, 22), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(11, 9, -7), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(11, 11, -13), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 11, 24), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(11, 12, -13), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 12, 22), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(11, 13, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_cobblestone", glm::vec3(11, 13, -8), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(11, 14, -14), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(11, 14, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(11, 14, -3), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(11, 14, 24), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(11, 15, -13), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 0, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 1, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 2, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 3, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 4, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 5, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 6, -7), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(12, 7, -10), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 7, -7), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(12, 7, -4), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(12, 7, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(12, 8, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -10), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(12, 8, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -8), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 8, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -6), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(12, 8, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 8, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -10), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -8), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 9, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 9, -5), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(12, 9, -4), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(12, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(12, 10, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -10), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(12, 10, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(12, 11, -12), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(12, 11, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -10), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -7), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(12, 11, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 11, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 12, -13), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(12, 12, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 12, -10), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(12, 12, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 12, -8), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(12, 12, -7), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(12, 12, -6), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(12, 12, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 12, -3), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(12, 13, -12), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(12, 13, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 13, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 13, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 13, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 13, -2), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(12, 14, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_cobblestone", glm::vec3(12, 14, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 14, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 14, -3), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(12, 15, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 15, -6), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(12, 15, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 15, -3), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(12, 16, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 16, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 16, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 16, -2), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 17, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 17, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 17, -2), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 18, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(12, 18, -2), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(13, 1, -4), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(13, 1, -3), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(13, 1, -2), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 7, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 7, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 7, -10), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(13, 8, -13), true));
				list->emplace_back(scene::miniBlockData("raw_gold", glm::vec3(13, 8, -12), true));
				list->emplace_back(scene::miniBlockData("raw_gold", glm::vec3(13, 8, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 8, -3), true));
				list->emplace_back(scene::miniBlockData("mossy_cobblestone", glm::vec3(13, 9, -13), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(13, 9, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 10, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 11, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 11, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 12, -14), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 12, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 12, -3), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(13, 15, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 15, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 16, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 17, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(13, 18, -3), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(13, 19, -10), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(13, 19, -6), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 0, -12), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 1, -12), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(14, 1, -4), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(14, 1, -3), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(14, 1, -2), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 5, -12), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 6, -13), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 6, -12), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 7, -13), true));
				list->emplace_back(scene::miniBlockData("magma", glm::vec3(14, 7, -12), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(14, 7, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 7, -10), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 8, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 9, -13), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(14, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 10, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 11, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(14, 11, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 12, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 12, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 13, -3), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(14, 13, -2), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 14, -3), true));
				list->emplace_back(scene::miniBlockData("magenta", glm::vec3(14, 14, 7), true));
				list->emplace_back(scene::miniBlockData("magenta", glm::vec3(14, 14, 8), true));
				list->emplace_back(scene::miniBlockData("magenta", glm::vec3(14, 14, 9), true));
				list->emplace_back(scene::miniBlockData("magenta", glm::vec3(14, 14, 10), true));
				list->emplace_back(scene::miniBlockData("magenta", glm::vec3(14, 14, 11), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 14), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 15), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 16), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 17), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 18), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 19), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 20), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 21), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 22), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 23), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 14, 24), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(14, 15, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 15, -3), true));
				list->emplace_back(scene::miniBlockData("pink", glm::vec3(14, 15, 5), true));
				list->emplace_back(scene::miniBlockData("pink", glm::vec3(14, 15, 6), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(14, 16, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 17, -3), true));
				list->emplace_back(scene::miniBlockData("magenta", glm::vec3(14, 17, 11), true));
				list->emplace_back(scene::miniBlockData("orange", glm::vec3(14, 17, 14), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(14, 18, -9), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(14, 18, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(14, 18, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 18, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 19, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 20, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(14, 21, -3), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 0, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 1, -8), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(15, 1, -4), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(15, 1, -3), true));
				list->emplace_back(scene::miniBlockData("slime_block", glm::vec3(15, 1, -2), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 2, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 3, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 4, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 5, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 6, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 7, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 7, -10), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 7, -8), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(15, 7, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 8, -13), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(15, 8, -12), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 8, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 8, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 9, -13), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 9, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 10, -13), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 10, -8), true));
				list->emplace_back(scene::miniBlockData("cobblestone", glm::vec3(15, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 11, -13), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 11, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 12, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 12, -3), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 13, -8), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(15, 13, -3), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 14, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 15, -8), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(15, 16, -13), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 16, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 16, -3), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 17, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 17, -3), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 18, -9), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 18, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(15, 18, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 18, -2), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 19, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 19, -3), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 20, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 20, -3), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 21, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(15, 21, -3), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 22, -8), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 23, -8), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 24, -8), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(15, 25, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 8, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 8, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 9, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 10, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 11, -13), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(16, 11, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 12, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 13, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 13, -2), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 14, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 15, -3), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(16, 16, -13), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(16, 16, -3), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(16, 18, -9), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(16, 18, -8), true));
				list->emplace_back(scene::miniBlockData("diamond_ore", glm::vec3(16, 18, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 19, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 20, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(16, 21, -3), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(17, 7, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 8, -3), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(17, 9, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 10, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 11, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 12, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 12, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 12, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 12, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 13, -3), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(17, 16, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 17, -3), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(17, 18, -5), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(17, 19, -10), true));
				list->emplace_back(scene::miniBlockData("glowstone", glm::vec3(17, 19, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 19, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 20, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(17, 21, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 8, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 8, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 9, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 10, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 11, -13), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(18, 11, -10), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(18, 11, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 12, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 12, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 12, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 12, -6), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(18, 12, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 13, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 13, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 13, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 14, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 15, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 15, -3), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(18, 16, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 16, -3), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(18, 17, -6), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(18, 17, -5), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(18, 18, -5), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(18, 18, -4), true));
				list->emplace_back(scene::miniBlockData("oak_leaves", glm::vec3(18, 19, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 19, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 20, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(18, 21, -3), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(19, 7, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 8, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 8, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 8, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 8, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 8, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 8, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 9, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -10), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 10, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -10), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(19, 11, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 11, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -10), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(19, 12, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 12, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -11), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(19, 13, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 13, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 14, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 14, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 14, -7), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(19, 14, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 14, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 15, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 15, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 15, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 15, -5), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(19, 16, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -9), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(19, 16, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -7), true));
				list->emplace_back(scene::miniBlockData("stone", glm::vec3(19, 16, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 16, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -13), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -11), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(19, 17, -10), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -6), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(19, 17, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 17, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -12), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -10), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -9), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -6), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(19, 18, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 18, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 19, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 19, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 19, -5), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(19, 19, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 19, -3), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(19, 20, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 20, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 20, -3), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 21, -4), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(19, 21, -3), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 0, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 1, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 2, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 3, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 4, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 5, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 6, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 7, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 8, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(20, 8, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(20, 8, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(20, 9, -8), true));
				list->emplace_back(scene::miniBlockData("marccoin_block", glm::vec3(20, 9, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(20, 9, -4), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(20, 10, -8), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(20, 10, -4), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(20, 11, -11), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(20, 11, -8), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(20, 11, -6), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(20, 11, -5), true));
				list->emplace_back(scene::miniBlockData("cracked_stone_bricks", glm::vec3(20, 12, -8), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(20, 12, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 16, -12), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 16, -11), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 17, -10), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 17, -9), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 18, -8), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 18, -7), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 18, -6), true));
				list->emplace_back(scene::miniBlockData("oak_log", glm::vec3(20, 18, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 9, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 9, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 9, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 9, -4), true));
				list->emplace_back(scene::miniBlockData("mossy_stone_bricks", glm::vec3(21, 10, -7), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 10, -6), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 10, -5), true));
				list->emplace_back(scene::miniBlockData("stone_bricks", glm::vec3(21, 11, -7), true));
				break;
			default:
				list->emplace_back(scene::miniBlockData("bedrock", glm::vec3(0,0,0), false, true));
				list->emplace_back(scene::miniBlockData("dirt", glm::vec3(0,1,0), false, true));
				list->emplace_back(scene::miniBlockData("dirt", glm::vec3(0,2,0), false, true));
				list->emplace_back(scene::miniBlockData("grass_block", glm::vec3(0,3,0), false, true));
				break;
    	}
	}

}